version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - setup_remote_docker
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker build -t cryptowater/qr_app .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push cryptowater/qr_app
